# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.cache/wt [current_project]
set_property parent.project_path D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/CounterDigit5.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/CounterDigit.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/SevenSegmentDisplay.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/FreqDiv.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/CountingUnit.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/TFlipFlop.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/Debouncer.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/ExecutionUnit.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/CommandUnit.vhd
  D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/sources_1/new/TOP.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/constrs_1/imports/Constraint files/Basys3_Master.xdc}}
set_property used_in_implementation false [get_files {{D:/UTCN/Sem2/DSD/Labs/Digital_Timer/ProjectCounter.srcs/constrs_1/imports/Constraint files/Basys3_Master.xdc}}]


synth_design -top TOP -part xc7a35tcpg236-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
